#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 14 12:39:20 2021

@author: priyanshu
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([95,85,80,70,60])
y = np.array([85,95,70,65,70])

n = np.size(x)

m_x,m_y = np.mean(x), np.mean(y)

ss_xy = np.sum(y*x) - (n*m_x*m_y)
ss_xx = np.sum(x*x) - n*m_x*m_x

b0_1 = ss_xy/ss_xx      #slope
b0_0 = m_y - b0_1*m_x   #intercept

y_pred = b0_0 + b0_1*x

print("intercept : " , b0_0)
print("slope : ", b0_1)

plt.scatter(x,y)
plt.plot(x,y_pred, color='r', marker='o')

from sklearn.metrics import r2_score

r2 = r2_score(y , y_pred)
print("fitting score : " , r2)
print(r2**0.5)
plt.show()
